#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = %cd%

CC = gcc.exe
CXX = g++.exe
AR = ar.exe
LD = gcc.exe
WINDRES = windres.exe

INC = 
CFLAGS = -Wall
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj\\Debug
DEP_DEBUG = 
OUT_DEBUG = bin\\Debug\\covid-unip.exe

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj\\Release
DEP_RELEASE = 
OUT_RELEASE = bin\\Release\\covid-unip.exe

OBJ_DEBUG = $(OBJDIR_DEBUG)\\utils.o $(OBJDIR_DEBUG)\\usecases\\usuario\\deletar.o $(OBJDIR_DEBUG)\\usecases\\usuario\\cadastrar.o $(OBJDIR_DEBUG)\\usecases\\paciente\\cadastrar.o $(OBJDIR_DEBUG)\\usecases\\login.o $(OBJDIR_DEBUG)\\usecases\\comorbidade\\deletar.o $(OBJDIR_DEBUG)\\usecases\\comorbidade\\cadastrar.o $(OBJDIR_DEBUG)\\repository\\usuario.o $(OBJDIR_DEBUG)\\repository\\pacientes-risco.o $(OBJDIR_DEBUG)\\repository\\paciente.o $(OBJDIR_DEBUG)\\repository\\comorbidade.o $(OBJDIR_DEBUG)\\repository\\comorbidade-paciente.o $(OBJDIR_DEBUG)\\presentation\\usuario.o $(OBJDIR_DEBUG)\\presentation\\read-structs.o $(OBJDIR_DEBUG)\\presentation\\principal.o $(OBJDIR_DEBUG)\\presentation\\paciente.o $(OBJDIR_DEBUG)\\presentation\\comorbidade.o $(OBJDIR_DEBUG)\\main.o $(OBJDIR_DEBUG)\\infra\\usuario.o $(OBJDIR_DEBUG)\\infra\\pacientes-risco.o $(OBJDIR_DEBUG)\\infra\\paciente.o $(OBJDIR_DEBUG)\\infra\\files.o $(OBJDIR_DEBUG)\\infra\\comorbidades.o $(OBJDIR_DEBUG)\\infra\\comorbidade-paciente.o $(OBJDIR_DEBUG)\\infra\\adadpter.o

OBJ_RELEASE = $(OBJDIR_RELEASE)\\utils.o $(OBJDIR_RELEASE)\\usecases\\usuario\\deletar.o $(OBJDIR_RELEASE)\\usecases\\usuario\\cadastrar.o $(OBJDIR_RELEASE)\\usecases\\paciente\\cadastrar.o $(OBJDIR_RELEASE)\\usecases\\login.o $(OBJDIR_RELEASE)\\usecases\\comorbidade\\deletar.o $(OBJDIR_RELEASE)\\usecases\\comorbidade\\cadastrar.o $(OBJDIR_RELEASE)\\repository\\usuario.o $(OBJDIR_RELEASE)\\repository\\pacientes-risco.o $(OBJDIR_RELEASE)\\repository\\paciente.o $(OBJDIR_RELEASE)\\repository\\comorbidade.o $(OBJDIR_RELEASE)\\repository\\comorbidade-paciente.o $(OBJDIR_RELEASE)\\presentation\\usuario.o $(OBJDIR_RELEASE)\\presentation\\read-structs.o $(OBJDIR_RELEASE)\\presentation\\principal.o $(OBJDIR_RELEASE)\\presentation\\paciente.o $(OBJDIR_RELEASE)\\presentation\\comorbidade.o $(OBJDIR_RELEASE)\\main.o $(OBJDIR_RELEASE)\\infra\\usuario.o $(OBJDIR_RELEASE)\\infra\\pacientes-risco.o $(OBJDIR_RELEASE)\\infra\\paciente.o $(OBJDIR_RELEASE)\\infra\\files.o $(OBJDIR_RELEASE)\\infra\\comorbidades.o $(OBJDIR_RELEASE)\\infra\\comorbidade-paciente.o $(OBJDIR_RELEASE)\\infra\\adadpter.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	cmd /c if not exist bin\\Debug md bin\\Debug
	cmd /c if not exist $(OBJDIR_DEBUG) md $(OBJDIR_DEBUG)
	cmd /c if not exist $(OBJDIR_DEBUG)\\usecases\\usuario md $(OBJDIR_DEBUG)\\usecases\\usuario
	cmd /c if not exist $(OBJDIR_DEBUG)\\usecases\\paciente md $(OBJDIR_DEBUG)\\usecases\\paciente
	cmd /c if not exist $(OBJDIR_DEBUG)\\usecases md $(OBJDIR_DEBUG)\\usecases
	cmd /c if not exist $(OBJDIR_DEBUG)\\usecases\\comorbidade md $(OBJDIR_DEBUG)\\usecases\\comorbidade
	cmd /c if not exist $(OBJDIR_DEBUG)\\repository md $(OBJDIR_DEBUG)\\repository
	cmd /c if not exist $(OBJDIR_DEBUG)\\presentation md $(OBJDIR_DEBUG)\\presentation
	cmd /c if not exist $(OBJDIR_DEBUG)\\infra md $(OBJDIR_DEBUG)\\infra

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)\\utils.o: utils.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c utils.c -o $(OBJDIR_DEBUG)\\utils.o

$(OBJDIR_DEBUG)\\usecases\\usuario\\deletar.o: usecases\\usuario\\deletar.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c usecases\\usuario\\deletar.c -o $(OBJDIR_DEBUG)\\usecases\\usuario\\deletar.o

$(OBJDIR_DEBUG)\\usecases\\usuario\\cadastrar.o: usecases\\usuario\\cadastrar.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c usecases\\usuario\\cadastrar.c -o $(OBJDIR_DEBUG)\\usecases\\usuario\\cadastrar.o

$(OBJDIR_DEBUG)\\usecases\\paciente\\cadastrar.o: usecases\\paciente\\cadastrar.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c usecases\\paciente\\cadastrar.c -o $(OBJDIR_DEBUG)\\usecases\\paciente\\cadastrar.o

$(OBJDIR_DEBUG)\\usecases\\login.o: usecases\\login.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c usecases\\login.c -o $(OBJDIR_DEBUG)\\usecases\\login.o

$(OBJDIR_DEBUG)\\usecases\\comorbidade\\deletar.o: usecases\\comorbidade\\deletar.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c usecases\\comorbidade\\deletar.c -o $(OBJDIR_DEBUG)\\usecases\\comorbidade\\deletar.o

$(OBJDIR_DEBUG)\\usecases\\comorbidade\\cadastrar.o: usecases\\comorbidade\\cadastrar.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c usecases\\comorbidade\\cadastrar.c -o $(OBJDIR_DEBUG)\\usecases\\comorbidade\\cadastrar.o

$(OBJDIR_DEBUG)\\repository\\usuario.o: repository\\usuario.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c repository\\usuario.c -o $(OBJDIR_DEBUG)\\repository\\usuario.o

$(OBJDIR_DEBUG)\\repository\\pacientes-risco.o: repository\\pacientes-risco.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c repository\\pacientes-risco.c -o $(OBJDIR_DEBUG)\\repository\\pacientes-risco.o

$(OBJDIR_DEBUG)\\repository\\paciente.o: repository\\paciente.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c repository\\paciente.c -o $(OBJDIR_DEBUG)\\repository\\paciente.o

$(OBJDIR_DEBUG)\\repository\\comorbidade.o: repository\\comorbidade.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c repository\\comorbidade.c -o $(OBJDIR_DEBUG)\\repository\\comorbidade.o

$(OBJDIR_DEBUG)\\repository\\comorbidade-paciente.o: repository\\comorbidade-paciente.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c repository\\comorbidade-paciente.c -o $(OBJDIR_DEBUG)\\repository\\comorbidade-paciente.o

$(OBJDIR_DEBUG)\\presentation\\usuario.o: presentation\\usuario.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c presentation\\usuario.c -o $(OBJDIR_DEBUG)\\presentation\\usuario.o

$(OBJDIR_DEBUG)\\presentation\\read-structs.o: presentation\\read-structs.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c presentation\\read-structs.c -o $(OBJDIR_DEBUG)\\presentation\\read-structs.o

$(OBJDIR_DEBUG)\\presentation\\principal.o: presentation\\principal.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c presentation\\principal.c -o $(OBJDIR_DEBUG)\\presentation\\principal.o

$(OBJDIR_DEBUG)\\presentation\\paciente.o: presentation\\paciente.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c presentation\\paciente.c -o $(OBJDIR_DEBUG)\\presentation\\paciente.o

$(OBJDIR_DEBUG)\\presentation\\comorbidade.o: presentation\\comorbidade.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c presentation\\comorbidade.c -o $(OBJDIR_DEBUG)\\presentation\\comorbidade.o

$(OBJDIR_DEBUG)\\main.o: main.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c main.c -o $(OBJDIR_DEBUG)\\main.o

$(OBJDIR_DEBUG)\\infra\\usuario.o: infra\\usuario.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c infra\\usuario.c -o $(OBJDIR_DEBUG)\\infra\\usuario.o

$(OBJDIR_DEBUG)\\infra\\pacientes-risco.o: infra\\pacientes-risco.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c infra\\pacientes-risco.c -o $(OBJDIR_DEBUG)\\infra\\pacientes-risco.o

$(OBJDIR_DEBUG)\\infra\\paciente.o: infra\\paciente.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c infra\\paciente.c -o $(OBJDIR_DEBUG)\\infra\\paciente.o

$(OBJDIR_DEBUG)\\infra\\files.o: infra\\files.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c infra\\files.c -o $(OBJDIR_DEBUG)\\infra\\files.o

$(OBJDIR_DEBUG)\\infra\\comorbidades.o: infra\\comorbidades.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c infra\\comorbidades.c -o $(OBJDIR_DEBUG)\\infra\\comorbidades.o

$(OBJDIR_DEBUG)\\infra\\comorbidade-paciente.o: infra\\comorbidade-paciente.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c infra\\comorbidade-paciente.c -o $(OBJDIR_DEBUG)\\infra\\comorbidade-paciente.o

$(OBJDIR_DEBUG)\\infra\\adadpter.o: infra\\adadpter.c
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c infra\\adadpter.c -o $(OBJDIR_DEBUG)\\infra\\adadpter.o

clean_debug: 
	cmd /c del /f $(OBJ_DEBUG) $(OUT_DEBUG)
	cmd /c rd bin\\Debug
	cmd /c rd $(OBJDIR_DEBUG)
	cmd /c rd $(OBJDIR_DEBUG)\\usecases\\usuario
	cmd /c rd $(OBJDIR_DEBUG)\\usecases\\paciente
	cmd /c rd $(OBJDIR_DEBUG)\\usecases
	cmd /c rd $(OBJDIR_DEBUG)\\usecases\\comorbidade
	cmd /c rd $(OBJDIR_DEBUG)\\repository
	cmd /c rd $(OBJDIR_DEBUG)\\presentation
	cmd /c rd $(OBJDIR_DEBUG)\\infra

before_release: 
	if exist %userprofile%\Desktop\COVID-UNIP.lnk del %userprofile%\Desktop\COVID-UNIP.lnk
	if exist %userprofile%\Desktop\ARQUIVOS-COVID-UNIP.lnk del /f %userprofile%\Desktop\ARQUIVOS-COVID-UNIP.lnk del %userprofile%\Desktop\ARQUIVOS-COVID-UNIP.lnk
	cmd /c if not exist bin\\Release md bin\\Release
	cmd /c if not exist $(OBJDIR_RELEASE) md $(OBJDIR_RELEASE)
	cmd /c if not exist $(OBJDIR_RELEASE)\\usecases\\usuario md $(OBJDIR_RELEASE)\\usecases\\usuario
	cmd /c if not exist $(OBJDIR_RELEASE)\\usecases\\paciente md $(OBJDIR_RELEASE)\\usecases\\paciente
	cmd /c if not exist $(OBJDIR_RELEASE)\\usecases md $(OBJDIR_RELEASE)\\usecases
	cmd /c if not exist $(OBJDIR_RELEASE)\\usecases\\comorbidade md $(OBJDIR_RELEASE)\\usecases\\comorbidade
	cmd /c if not exist $(OBJDIR_RELEASE)\\repository md $(OBJDIR_RELEASE)\\repository
	cmd /c if not exist $(OBJDIR_RELEASE)\\presentation md $(OBJDIR_RELEASE)\\presentation
	cmd /c if not exist $(OBJDIR_RELEASE)\\infra md $(OBJDIR_RELEASE)\\infra

after_release: 
	echo Set oWS = WScript.CreateObject("WScript.Shell") > CreateShortcut.vbs
	echo sLinkFile = "%userprofile%\Desktop\COVID-UNIP.lnk" >> CreateShortcut.vbs
	echo Set oLink = oWS.CreateShortcut(sLinkFile) >> CreateShortcut.vbs
	echo oLink.TargetPath = "%cd%\bin\Release\covid-unip.exe" >> CreateShortcut.vbs
	echo oLink.WorkingDirectory = "%cd%\bin\Release" >> CreateShortcut.vbs
	echo oLink.Description = "Programa para cadastro de pacientes com Covid UNIP" >> CreateShortcut.vbs
	echo oLink.IconLocation = "%cd%\icon.bmp" >> CreateShortcut.vbs
	echo oLink.Save >> CreateShortcut.vbs
	cscript CreateShortcut.vbs
	del CreateShortcut.vbs
	echo Set oWS = WScript.CreateObject("WScript.Shell") > CreateShortcut.vbs
	echo sLinkFile = "%userprofile%\Desktop\ARQUIVOS-COVID-UNIP.lnk" >> CreateShortcut.vbs
	echo Set oLink = oWS.CreateShortcut(sLinkFile) >> CreateShortcut.vbs
	echo oLink.TargetPath = "%cd%\bin\Release" >> CreateShortcut.vbs
	echo oLink.WorkingDirectory = "%cd%\bin\Release" >> CreateShortcut.vbs
	echo oLink.Description = "Pasta com os arquivos do programa Covid UNIP" >> CreateShortcut.vbs
	echo oLink.IconLocation = "%SystemRoot%\System32\SHELL32.dll,3" >> CreateShortcut.vbs
	echo oLink.Save >> CreateShortcut.vbs
	cscript CreateShortcut.vbs
	del CreateShortcut.vbs

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)\\utils.o: utils.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c utils.c -o $(OBJDIR_RELEASE)\\utils.o

$(OBJDIR_RELEASE)\\usecases\\usuario\\deletar.o: usecases\\usuario\\deletar.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c usecases\\usuario\\deletar.c -o $(OBJDIR_RELEASE)\\usecases\\usuario\\deletar.o

$(OBJDIR_RELEASE)\\usecases\\usuario\\cadastrar.o: usecases\\usuario\\cadastrar.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c usecases\\usuario\\cadastrar.c -o $(OBJDIR_RELEASE)\\usecases\\usuario\\cadastrar.o

$(OBJDIR_RELEASE)\\usecases\\paciente\\cadastrar.o: usecases\\paciente\\cadastrar.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c usecases\\paciente\\cadastrar.c -o $(OBJDIR_RELEASE)\\usecases\\paciente\\cadastrar.o

$(OBJDIR_RELEASE)\\usecases\\login.o: usecases\\login.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c usecases\\login.c -o $(OBJDIR_RELEASE)\\usecases\\login.o

$(OBJDIR_RELEASE)\\usecases\\comorbidade\\deletar.o: usecases\\comorbidade\\deletar.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c usecases\\comorbidade\\deletar.c -o $(OBJDIR_RELEASE)\\usecases\\comorbidade\\deletar.o

$(OBJDIR_RELEASE)\\usecases\\comorbidade\\cadastrar.o: usecases\\comorbidade\\cadastrar.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c usecases\\comorbidade\\cadastrar.c -o $(OBJDIR_RELEASE)\\usecases\\comorbidade\\cadastrar.o

$(OBJDIR_RELEASE)\\repository\\usuario.o: repository\\usuario.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c repository\\usuario.c -o $(OBJDIR_RELEASE)\\repository\\usuario.o

$(OBJDIR_RELEASE)\\repository\\pacientes-risco.o: repository\\pacientes-risco.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c repository\\pacientes-risco.c -o $(OBJDIR_RELEASE)\\repository\\pacientes-risco.o

$(OBJDIR_RELEASE)\\repository\\paciente.o: repository\\paciente.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c repository\\paciente.c -o $(OBJDIR_RELEASE)\\repository\\paciente.o

$(OBJDIR_RELEASE)\\repository\\comorbidade.o: repository\\comorbidade.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c repository\\comorbidade.c -o $(OBJDIR_RELEASE)\\repository\\comorbidade.o

$(OBJDIR_RELEASE)\\repository\\comorbidade-paciente.o: repository\\comorbidade-paciente.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c repository\\comorbidade-paciente.c -o $(OBJDIR_RELEASE)\\repository\\comorbidade-paciente.o

$(OBJDIR_RELEASE)\\presentation\\usuario.o: presentation\\usuario.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c presentation\\usuario.c -o $(OBJDIR_RELEASE)\\presentation\\usuario.o

$(OBJDIR_RELEASE)\\presentation\\read-structs.o: presentation\\read-structs.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c presentation\\read-structs.c -o $(OBJDIR_RELEASE)\\presentation\\read-structs.o

$(OBJDIR_RELEASE)\\presentation\\principal.o: presentation\\principal.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c presentation\\principal.c -o $(OBJDIR_RELEASE)\\presentation\\principal.o

$(OBJDIR_RELEASE)\\presentation\\paciente.o: presentation\\paciente.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c presentation\\paciente.c -o $(OBJDIR_RELEASE)\\presentation\\paciente.o

$(OBJDIR_RELEASE)\\presentation\\comorbidade.o: presentation\\comorbidade.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c presentation\\comorbidade.c -o $(OBJDIR_RELEASE)\\presentation\\comorbidade.o

$(OBJDIR_RELEASE)\\main.o: main.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c main.c -o $(OBJDIR_RELEASE)\\main.o

$(OBJDIR_RELEASE)\\infra\\usuario.o: infra\\usuario.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c infra\\usuario.c -o $(OBJDIR_RELEASE)\\infra\\usuario.o

$(OBJDIR_RELEASE)\\infra\\pacientes-risco.o: infra\\pacientes-risco.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c infra\\pacientes-risco.c -o $(OBJDIR_RELEASE)\\infra\\pacientes-risco.o

$(OBJDIR_RELEASE)\\infra\\paciente.o: infra\\paciente.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c infra\\paciente.c -o $(OBJDIR_RELEASE)\\infra\\paciente.o

$(OBJDIR_RELEASE)\\infra\\files.o: infra\\files.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c infra\\files.c -o $(OBJDIR_RELEASE)\\infra\\files.o

$(OBJDIR_RELEASE)\\infra\\comorbidades.o: infra\\comorbidades.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c infra\\comorbidades.c -o $(OBJDIR_RELEASE)\\infra\\comorbidades.o

$(OBJDIR_RELEASE)\\infra\\comorbidade-paciente.o: infra\\comorbidade-paciente.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c infra\\comorbidade-paciente.c -o $(OBJDIR_RELEASE)\\infra\\comorbidade-paciente.o

$(OBJDIR_RELEASE)\\infra\\adadpter.o: infra\\adadpter.c
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c infra\\adadpter.c -o $(OBJDIR_RELEASE)\\infra\\adadpter.o

clean_release: 
	cmd /c del /f $(OBJ_RELEASE) $(OUT_RELEASE)
	cmd /c rd bin\\Release
	cmd /c rd $(OBJDIR_RELEASE)
	cmd /c rd $(OBJDIR_RELEASE)\\usecases\\usuario
	cmd /c rd $(OBJDIR_RELEASE)\\usecases\\paciente
	cmd /c rd $(OBJDIR_RELEASE)\\usecases
	cmd /c rd $(OBJDIR_RELEASE)\\usecases\\comorbidade
	cmd /c rd $(OBJDIR_RELEASE)\\repository
	cmd /c rd $(OBJDIR_RELEASE)\\presentation
	cmd /c rd $(OBJDIR_RELEASE)\\infra

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

