name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Windows:
    name: build-windows
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      with:
          submodules: recursive
    - name: Running Make (windows)
      run: |
        cd ${{ github.workspace }}
        ./INSTALADOR.exe
